language: cpp
sudo: required
matrix:
    include:
        os: linux
        addons:
            apt:
                sources:
                    ubuntu-toolchain-r-test
                packages:
                    - g++-5
                    - gcc-5
                    - cmake
                    - libboost-dev
                    - libsfml-dev
        env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
    - eval "${MATRIX_EVAL}"
install:
    - git clone -b 0.7 --single-branch https://github.com/texus/TGUI.git tgui
    - cd tgui
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
