language: cpp
sudo: required
install:
    - sudo apt install cmake -y
    - sudo apt install libboost-dev -y
    - sudo apt libsfml-dev -y
    - git clone -b 0.7 --single-branch https://github.com/texus/TGUI.git tgui
    - cd tgui
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
